import type { Stem, TenGod } from '@mylife/bazi-domain';

/** 일간이 첫 번째 키, 대상 천간이 두 번째 키다. */
export const TEN_GODS = {
  甲: {
    甲: 'peer',
    乙: 'rob_wealth',
    丙: 'eating_god',
    丁: 'hurting_officer',
    戊: 'indirect_wealth',
    己: 'direct_wealth',
    庚: 'seven_killings',
    辛: 'direct_officer',
    壬: 'indirect_resource',
    癸: 'direct_resource',
  },
  乙: {
    甲: 'rob_wealth',
    乙: 'peer',
    丙: 'hurting_officer',
    丁: 'eating_god',
    戊: 'direct_wealth',
    己: 'indirect_wealth',
    庚: 'direct_officer',
    辛: 'seven_killings',
    壬: 'direct_resource',
    癸: 'indirect_resource',
  },
  丙: {
    甲: 'indirect_resource',
    乙: 'direct_resource',
    丙: 'peer',
    丁: 'rob_wealth',
    戊: 'eating_god',
    己: 'hurting_officer',
    庚: 'indirect_wealth',
    辛: 'direct_wealth',
    壬: 'seven_killings',
    癸: 'direct_officer',
  },
  丁: {
    甲: 'direct_resource',
    乙: 'indirect_resource',
    丙: 'rob_wealth',
    丁: 'peer',
    戊: 'hurting_officer',
    己: 'eating_god',
    庚: 'direct_wealth',
    辛: 'indirect_wealth',
    壬: 'direct_officer',
    癸: 'seven_killings',
  },
  戊: {
    甲: 'seven_killings',
    乙: 'direct_officer',
    丙: 'indirect_resource',
    丁: 'direct_resource',
    戊: 'peer',
    己: 'rob_wealth',
    庚: 'eating_god',
    辛: 'hurting_officer',
    壬: 'indirect_wealth',
    癸: 'direct_wealth',
  },
  己: {
    甲: 'direct_officer',
    乙: 'seven_killings',
    丙: 'direct_resource',
    丁: 'indirect_resource',
    戊: 'rob_wealth',
    己: 'peer',
    庚: 'hurting_officer',
    辛: 'eating_god',
    壬: 'direct_wealth',
    癸: 'indirect_wealth',
  },
  庚: {
    甲: 'indirect_wealth',
    乙: 'direct_wealth',
    丙: 'seven_killings',
    丁: 'direct_officer',
    戊: 'indirect_resource',
    己: 'direct_resource',
    庚: 'peer',
    辛: 'rob_wealth',
    壬: 'eating_god',
    癸: 'hurting_officer',
  },
  辛: {
    甲: 'direct_wealth',
    乙: 'indirect_wealth',
    丙: 'direct_officer',
    丁: 'seven_killings',
    戊: 'direct_resource',
    己: 'indirect_resource',
    庚: 'rob_wealth',
    辛: 'peer',
    壬: 'hurting_officer',
    癸: 'eating_god',
  },
  壬: {
    甲: 'eating_god',
    乙: 'hurting_officer',
    丙: 'indirect_wealth',
    丁: 'direct_wealth',
    戊: 'seven_killings',
    己: 'direct_officer',
    庚: 'indirect_resource',
    辛: 'direct_resource',
    壬: 'peer',
    癸: 'rob_wealth',
  },
  癸: {
    甲: 'hurting_officer',
    乙: 'eating_god',
    丙: 'direct_wealth',
    丁: 'indirect_wealth',
    戊: 'direct_officer',
    己: 'seven_killings',
    庚: 'direct_resource',
    辛: 'indirect_resource',
    壬: 'rob_wealth',
    癸: 'peer',
  },
} as const satisfies Readonly<Record<Stem, Readonly<Record<Stem, TenGod>>>>;

/** 동일 정의를 사용하는 100개 셀의 공통 출처. */
export const TEN_GODS_SOURCE = {
  ruleCode: 'TEN_GODS',
  sourceIds: ['SMMT-05'],
  locator: '論古人立印食官財名義; 일간 기준 생극·음양의 서비스 코드 정규화',
} as const;
